Verify prelude against Official metamath (#48)
* Run yapf (Latest version)

* Update dependency versions to newer ones

* yapf

* Update total function attributes

* Add the official metamath as a dependency

* scripts/test: Use the official metamath to implementation to verify all hand-written proofs

* Fix some compressed proofs

* theory/kore-reachability.mm: Update proofs with compression done by official metamath

* theory/kore-reachability.mm: Replace failing proofs with axioms

These are due to a bug in the substitution/notation  procedures in the ITP

* scripts/test: Verify theories/prelude.mm

* Install types-pyyaml hints

* itp: Allow printing uncompressed proofs.

There appears to be a bug when generating substitution related proofs.

* update type hints for newer mypy/python

* scripts/test: Initialize the metamath repo

* scripts/test: Add metamath to path

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -2,6 +2,58 @@
 
 set -euo pipefail
 
-yapf --recursive --diff ml scripts tests
-mypy --strict --no-incremental ml scripts tests
-pytest "$@" --ignore=deps
+# Dependencies
+# ============
+
+build-metamath() {
+    (   git submodule update --init --recursive deps/metamath-exe/
+        cd deps/metamath-exe/src
+        gcc m*.c -o metamath
+    )
+    PATH="$(pwd)/deps/metamath-exe/src:$PATH"
+}
+
+# Tests
+# =====
+
+static-checks() {
+    yapf --recursive --diff ml scripts tests
+    mypy --strict --no-incremental ml scripts tests
+}
+
+unit-tests() {
+    pytest "$@" --ignore=deps
+}
+
+metamath-verify() {
+    # Modified from https://github.com/metamath/set.mm/blob/develop/scripts/verify
+    # We should find a cleaner way of doing this long term.
+    mmfile=$1; shift
+    log_file=.build/${mmfile}.log
+    echo "Checking '$mmfile'"
+    mkdir -p $(dirname "$log_file")
+    metamath > "$log_file" << COMMANDS
+set echo on
+set scroll continuous
+read '${mmfile}'
+verify proof *
+quit
+COMMANDS
+    # Get status, which is false (nonzero) if an error or warning was found.
+    ! grep -E '[?]Error|[?]Warning' < "$log_file" > /dev/null || {
+        echo "FAILED. See: $log_file";
+        return 1;
+    }
+}
+
+metamath-verify-all() {
+    for f in "$@"; do
+        metamath-verify "$f"
+    done
+}
+
+static-checks
+unit-tests
+build-metamath
+metamath-verify-all theory/matching-logic*.mm theory/prelude.mm
+
